[General]
Button_border_color=@Variant(\0\0\0\x43\x1\xff\xff\x80\x80\x80\x80\x80\x80\0\0)
Button_fill_color=@Variant(\0\0\0\x43\x1\xff\xff\xa0\xa0\xa0\xa0\xa4\xa4\0\0)
Button_line_style=0
Button_line_thickness=0
Button_text_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
Button_text_font=Helvetica
Button_text_size=0
Check_box_border_color=@Variant(\0\0\0\x43\x1\xff\xff\xa0\xa0\xa0\xa0\xa4\xa4\0\0)
Check_box_fill_color=@Variant(\0\0\0\x43\x1\0\0\0\0\0\0\0\0\0\0)
Check_box_line_style=0
Check_box_line_thickness=0
Check_box_style=0
Check_box_text_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
Combo_box_border_color=@Variant(\0\0\0\x43\x1\xff\xff\xa0\xa0\xa0\xa0\xa4\xa4\0\0)
Combo_box_fill_color=@Variant(\0\0\0\x43\x1\0\0\0\0\0\0\0\0\0\0)
Combo_box_line_style=0
Combo_box_line_thickness=0
Combo_box_text_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
Combo_box_text_font=Helvetica
Combo_box_text_size=0
DefaultFillAlpha=1
DefaultLineWidth=1
DefaultPathColorFill=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
DefaultPathColorStroke=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
DefaultPathFillType=1
DefaultPathStrokeType=1
DefaultStrokeAlpha=1
Edit_Box_border_color=@Variant(\0\0\0\x43\x1\0\0\0\0\0\0\0\0\0\0)
Edit_Box_fill_color=@Variant(\0\0\0\x43\x1\0\0\0\0\0\0\0\0\0\0)
Edit_Box_line_style=0
Edit_Box_line_thickness=0
Edit_Box_text_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
Edit_Box_text_font=Helvetica
Edit_Box_text_size=0
List_box_border_color=@Variant(\0\0\0\x43\x1\xff\xff\xa0\xa0\xa0\xa0\xa4\xa4\0\0)
List_box_fill_color=@Variant(\0\0\0\x43\x1\0\0\0\0\0\0\0\0\0\0)
List_box_line_style=0
List_box_line_thickness=0
List_box_text_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
List_box_text_font=Helvetica
List_box_text_size=0
Radio_button_border_color=@Variant(\0\0\0\x43\x1\xff\xff\xa0\xa0\xa0\xa0\xa4\xa4\0\0)
Radio_button_fill_color=@Variant(\0\0\0\x43\x1\0\0\0\0\0\0\0\0\0\0)
Radio_button_line_style=0
Radio_button_line_thickness=0
Radio_button_style=1
Radio_button_text_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
Signature_border_color=@Variant(\0\0\0\x43\x1\xff\xff\xa0\xa0\xa0\xa0\xa4\xa4\0\0)
Signature_fill_color=@Variant(\0\0\0\x43\x1\0\0\0\0\0\0\0\0\0\0)
Signature_line_style=0
Signature_line_thickness=0
Signature_text_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
Signature_text_font=Helvetica
Units=Points
antialiasing_image=true
antialiasing_path=true
antialiasing_text=true
app_style=Light
change_font=true
change_font_exact=false
check_updates=0
close_app_normal=true
create_backup_file=true
default_font=Helvetica
default_font_color=4278190080
default_font_size=12
enable_javascript=true
enable_scroll_wheel_zooming=true
highlight_opacity=100
link_highlight=1
main-version=4389
note_type=2
open_one_window=true
parse_separate_all_forms=true
popup_opacity=60
restore_last_session_application=false
restore_last_session_files=false
show_icons=true
show_start_page=true
use_default_email_program=true

[DistanceTool]
units=pt
value=1

[resent_files_history]
size=0

[tesseract_ocr_langs]
size=0
